"""Verify the token-matching checks of Decision Log 3.2.3 on assembled prompts.

For each replacement condition and each source_id given (default: the
example 7), the full prompt is built with build_inputs.build_prompt for
baseline and for the condition, both are tokenised with o200k_base as a
whole (never by parts), and for every site of that condition:
  (1) the number of tokens starting inside the replaced span (replaced
      text plus the line's newline, see manual_sites.py) equals the
      baseline count;
  (2) the index of the first token starting at or after the span end,
      i.e. the first preserved token of the next line, equals the baseline
      index;
  (3) the total token count of the prompt equals the baseline total.
Any mismatch prints line, original/replacement counts, index difference,
and the script exits 1.

The condition files are read from manual/ as generated by
build_conditions.py; nothing is regenerated here. Reused in roadmap 13 for
all sampled source_ids: pass them as arguments.

Output: reports/token-matching-check-<date>.txt
Usage (repository root, conda base with tiktoken 0.14.0):
    python scripts/check_token_matching.py            # source_id 7
    python scripts/check_token_matching.py 7 42 913   # any list
"""

import sys
from datetime import datetime

import tiktoken

from build_inputs import MANUAL_HEADER, git_commit_hash, prompt_parts
from manual_sites import (
    CONDITION_FILES, ENCODING_NAME, EXAMPLE_SOURCE_ID, LETTER_CONDITION,
    REPORTS_DIR, read_lines, read_manifest, token_starts,
)


def site_spans(cond_lines: list[str], sites: list[dict]) -> dict[int, tuple[int, int]]:
    """Return {site_id: (start, end)} char offsets of the measured spans (text + newline)."""
    line_start = []
    pos = 0
    for l in cond_lines:
        line_start.append(pos)
        pos += len(l) + 1
    spans = {}
    for s in sites:
        i = s["line_no"] - 1
        a = line_start[i] + len(s["preserved_prefix"])
        spans[s["site_id"]] = (a, line_start[i] + len(cond_lines[i]) + 1)  # + newline
    return spans


def prompt_and_offset(source_id: int, condition: str) -> tuple[str, int]:
    """Return the assembled prompt and the offset of the manual body in it."""
    parts = prompt_parts(source_id, condition)
    full = "\n\n".join(parts.values())
    return full, len(parts["task"]) + 2 + len(MANUAL_HEADER) + 1


def measure_sites(starts: list[int], spans: dict[int, tuple[int, int]], off: int) -> dict[int, tuple[int, int]]:
    """Return {site_id: (count, next_index)} for token start offsets."""
    res = {}
    for sid, (a, b) in spans.items():
        a += off
        b += off
        res[sid] = (sum(1 for s in starts if a <= s < b),
                    next((i for i, s in enumerate(starts) if s >= b), len(starts)))
    return res


def main(argv: list[str]) -> int:
    source_ids = [int(a) for a in argv] or [EXAMPLE_SOURCE_ID]
    enc = tiktoken.get_encoding(ENCODING_NAME)
    manifest = read_manifest()
    base_lines = read_lines(CONDITION_FILES["baseline"])
    for r in manifest:
        assert base_lines[r["line_no"] - 1] == r["preserved_prefix"] + r["replaced_text"], r["site_id"]
    cond_lines = {c: read_lines(CONDITION_FILES[c]) for c in LETTER_CONDITION.values()}

    now = datetime.now().astimezone()
    out = [
        "Token matching check (Decision Log 3.2.3)",
        f"Generated at: {now.isoformat(timespec='seconds')}",
        f"Script commit: {git_commit_hash()}",
        f"tiktoken {tiktoken.__version__}, encoding {ENCODING_NAME}",
        f"source_ids: {source_ids}",
        "",
    ]
    n_fail = 0
    n_sites = 0
    for sid in source_ids:
        base_prompt, off = prompt_and_offset(sid, "baseline")
        base_starts = token_starts(enc, base_prompt)
        base_spans = site_spans(base_lines, manifest)
        base_m = measure_sites(base_starts, base_spans, off)
        for cond in LETTER_CONDITION.values():
            letter = [k for k, v in LETTER_CONDITION.items() if v == cond][0]
            sites = [r for r in manifest if r["condition"] == letter]
            prompt, off_c = prompt_and_offset(sid, cond)
            assert off_c == off
            starts = token_starts(enc, prompt)
            spans = site_spans(cond_lines[cond], sites)
            m = measure_sites(starts, spans, off)
            fails = []
            for r in sites:
                wc, wn = base_m[r["site_id"]]
                gc, gn = m[r["site_id"]]
                if (wc, wn) != (gc, gn):
                    fails.append(f"    line {r['line_no']:4d} site {r['site_id']:3d}: "
                                 f"tokens original={wc} replacement={gc}  next-token index diff={gn - wn}")
            total_ok = len(starts) == len(base_starts)
            status = "PASS" if not fails and total_ok else "FAIL"
            n_fail += status == "FAIL"
            n_sites += len(sites)
            out.append(f"{status}  source_id={sid} {cond:28s} sites={len(sites):2d} "
                       f"(1)(2) mismatches={len(fails)}  (3) total {len(starts)} vs baseline {len(base_starts)}")
            out += fails
    out += ["", f"RESULT: {n_fail} failing condition/source_id pairs; {n_sites} site checks run"]
    REPORTS_DIR.mkdir(exist_ok=True)
    report = REPORTS_DIR / f"token-matching-check-{now:%Y-%m-%d}.txt"
    report.write_text("\n".join(out) + "\n", encoding="utf-8")
    print("\n".join(out))
    print(f"Wrote {report}")
    return 1 if n_fail else 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
